x = input('Digite qualquer coisa: ')
print('O tipo primitivo desse valor é {}'.format(type(x)))
print('Só tem espaço? {}'.format(x.isspace()))
print('Pode printar? {}'.format(x.isprintable()))
print('É um número? {}'.format(x.isnumeric()))
print('É alfabético? {}'.format(x.isalpha()))
print('É alfanumérico? {}'.format(x.isalnum()))
print('Está em maiúscula? {}'.format(x.isupper()))
print('Está em minuscula? {}'.format(x.islower()))
print('Está capitalizada? {}'.format(x.istitle()))
